Update update-libraries.yml

diff --git a/.github/workflows/update-libraries.yml b/.github/workflows/update-libraries.yml
--- a/.github/workflows/update-libraries.yml
+++ b/.github/workflows/update-libraries.yml
@@ -30,10 +30,19 @@ jobs:
     - name: Clean Go module cache
       run: |
         go clean -modcache
+
+    # export LIST="https://raw.githubusercontent.com/common-github-actions/main/.github/configs/dell-libraries-list.txt"
+    - name: Grab Dell libraries file
+      continue-on-error: true
+      run: |
+        export LIST="https://raw.githubusercontent.com/shaynafinocchiaro/test-common-github-actions/main/.github/configs/dell-libraries-list.txt"
+        curl -O -f $LIST
+
     - name: Update packages to latest versions in go.mod
       run: |
         for REPO in "${REPOS[@]}"; do
           echo "Processing $REPO"
+
           if [[ $REPO == "github.com/dell/dell-csi-extensions" ]]; then
             SUBPACKAGES=("common" "migration" "podmon" "replication" "volumeGroupSnapshot")
             for SUBPACKAGE in "${SUBPACKAGES[@]}"; do
@@ -46,20 +55,23 @@ jobs:
             done
             continue
           fi
-          MODULE_PATH=$(go list -m -f '{{.Path}}' $REPO  2>/dev/null)
+
+          MODULE_PATH=$(go list -m -f '{{.Path}}' $REPO 2>/dev/null)
           if [[ $? -ne 0 ]]; then
             echo "Skipping $REPO: not a known dependency"
             continue
           fi
+
           if [[ $MODULE_PATH == *"/v2"* ]]; then
             echo "Updating ${REPO}/v2"
-            go get ${REPO}/v2@latest  || echo "Failed to update ${REPO}/v2"
+            go get ${REPO}/v2@latest || echo "Failed to update ${REPO}/v2"
           else
-            echo "Updating $REPO@latest"
+            echo "Updating ${REPO}@latest"
             go get ${REPO}@latest || echo "Failed to update ${REPO}"
           fi
-        done < configs/dell-libraries-list.txt
+        done < dell-libraries-list.txt
         go mod tidy
+
     # Needed for signing commits using Github App tokens
     # See: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#commit-signing
     - uses: actions/create-github-app-token@v1.11.1
